@startuml
left to right direction
skinparam packageStyle rectangle
skinparam actorStyle hollow
actor Teacher #line:blue

rectangle UsecaseTeacher{
(login) --> (borrow up to 4 items)
Teacher --> (login)
(login) --> (view past lendings)
(view past lendings) <.> (check past details of loan):<<extends>>
(borrow up to 4 items) -.> (barcode gets scanned):<<extends>>
(borrow up to 4 items) -.> (item state is reserved):<<include>>
(barcode gets scanned) -.> (pickup date get registered):<<include>>
(barcode gets scanned) -.> (item state is borrowed):<<include>>
Teacher --> (return borrowed item)
(return borrowed item).> (scan barcode):<<extends>>
(scan barcode).>(item state is returned):<<include>>
(borrow up to 4 items) .> (Item wasn't picked up):<<extends>>
(Item wasn't picked up) -.> (item state is extended):<<include>>


}
@enduml